### ISSUE TITLE
Failed to parse JSON output on iOS 16.6.1

### ISSUE THREAD

**Issue by peterburk** [0xkuj/IPARanger#39]
Hi! 
Just tried using using 2 accounts (primary with no 2FA enabled, spare with 2FA enabled) on iOS 16.6.1 on iPhone SE 2G (arm64). 
Got the error "Failed to parse JSON output"

![Image](https://github.com/user-attachments/assets/7e3d3cc8-4379-411c-b2fb-0fd3d54351d4)
![Image](https://github.com/user-attachments/assets/ef4894eb-7cdb-49e4-8ddb-566c4bb09c12)

It's "semi-jailbroken" with Trollstore and nathanlr. Installation was with Sileo. 

Are there logs somewhere that might help with the bug investigation?

Meanwhile, on iPhone SE 1G on iOS 15.8 (arm), jailbroken with palera1n -f, the login worked, cleared 2FA authentication, and successfully downloaded a couple of IPA files. 
Installation was with Filza. 

Thanks for making an alternative app store, this is great for backup purposes!

**Comment by 0xkuj** [comment]
i am not sure, this wasnt tested on semi jailbreaks. maybe try the rootful version even though i doubt it will work

**Comment by peterburk** [comment]
Just tried on v2.0, and that gave the same error "Failed to parse JSON output".

**Comment by Marwinm187** [comment]
> i am not sure, this wasnt tested on semi jailbreaks. maybe try the rootful version even though i doubt it will work

Can you make a Semi-jailbraek Version

**Comment by 0xkuj** [comment]
fixed in 2.5.2

**Comment by peterburk** [comment]
Still happens with 2.6.0. 

<img width="750" height="1334" alt="Image" src="https://github.com/user-attachments/assets/4f54d506-f2df-4656-8131-36401b40e4f3" />

**Comment by 0xkuj** [comment]
What jailbreak and iOS?

**Comment by peterburk** [comment]
NathanLR, 16.6.1.

**Comment by 0xkuj** [comment]
This explains it, there is no semi jailbreak support at the moment. Highly recommend to use dopamine
